// <auto-generated />
using System;
using KerberGestaoRegraDeNegocio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KerberGestaoRegraDeNegocio.Migrations
{
    [DbContext(typeof(kerbergestaoContext))]
    [Migration("20230222012353_CriandoComentariosOs")]
    partial class CriandoComentariosOs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("KerberGestaoRegraDeNegocio.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCliente");

                    b.Property<string>("BairroCliente")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("bairroCliente");

                    b.Property<string>("CelularCliente")
                        .HasColumnType("longtext")
                        .HasColumnName("celularCliente");

                    b.Property<string>("CidadeCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("cidadeCliente");

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cpfCliente");

                    b.Property<string>("EnderecoCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("enderecoCliente");

                    b.Property<string>("EstadoCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("estadoCliente");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nomeCliente");

                    b.Property<string>("StatusCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("statusCliente");

                    b.Property<string>("TelefoneCliente")
                        .HasColumnType("longtext")
                        .HasColumnName("telefoneCliente");

                    b.HasKey("IdCliente")
                        .HasName("PRIMARY");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("KerberGestaoRegraDeNegocio.Models.Entities.ComentariosOrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdOrdemServico")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ComentariosOrdemServico");
                });

            modelBuilder.Entity("KerberGestaoRegraDeNegocio.Models.Entities.Orcamento", b =>
                {
                    b.Property<int>("IdOrcamentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idOrcamentos");

                    b.Property<string>("NomeOrcamento")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nomeOrcamento");

                    b.Property<int>("StatusOrcamento")
                        .HasColumnType("int")
                        .HasColumnName("statusOrcamento");

                    b.HasKey("IdOrcamentos")
                        .HasName("PRIMARY");

                    b.ToTable("orcamentos", (string)null);
                });

            modelBuilder.Entity("KerberGestaoRegraDeNegocio.Models.Entities.Ordemservico", b =>
                {
                    b.Property<int>("IdOrdemServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idOrdemServico");

                    b.Property<string>("Detalhamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detalhamento");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("idCliente");

                    b.Property<int>("IdOrcamento")
                        .HasColumnType("int")
                        .HasColumnName("idOrcamento");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("titulo");

                    b.HasKey("IdOrdemServico")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCliente" }, "cliente_fk_idx");

                    b.HasIndex(new[] { "IdOrcamento" }, "orcamento_fk_idx");

                    b.ToTable("ordemservico", (string)null);
                });

            modelBuilder.Entity("KerberGestaoRegraDeNegocio.Models.Entities.Projeto", b =>
                {
                    b.Property<int>("IdProjeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idProjeto");

                    b.Property<string>("NomeProjeto")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nomeProjeto");

                    b.Property<int>("StatusProjeto")
                        .HasColumnType("int")
                        .HasColumnName("statusProjeto");

                    b.HasKey("IdProjeto")
                        .HasName("PRIMARY");

                    b.ToTable("projetos", (string)null);
                });

            modelBuilder.Entity("KerberGestaoRegraDeNegocio.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
